sudo: false
language: python
dist: xenial
python:
  - 2.7
  - 3.7
cache:
  pip: true
env:
  matrix:
    - JULIA_VERSION=1.0
    - JULIA_VERSION=1.1
    - JULIA_VERSION=1.2
install:
  - source tools/setup_travis.sh $HOME/miniconda $TRAVIS_PYTHON_VERSION
  - python -V
  - export IMP_TMP_DIR=/tmp
  - rm -f ${CONDA_PREFIX}/lib/libimp_hmc.so*
before_script: # Set up unique dependencies
  - echo ./tools/install-julia.sh "$JULIA_VERSION"
  - ./tools/install-julia.sh "$JULIA_VERSION"
  - pip install pyjulia
  - python -c 'import julia; julia.install()'
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/salilab/HMCUtilities.jl"))'
  - python -c 'import julia; import.julia.HMCUtilities'
  - pip install arviz
script:
  - mkdir build
  - cd build
  - if test "${TRAVIS_PYTHON_VERSION}" = "2.7" ; then PY2=on; else PY2=off; fi
  - cmake .. -DIMP_DIR=${CONDA_PREFIX}/lib/cmake/IMP -DUSE_PYTHON2=${PY2} -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage"
  - make
  - ./setup_environment.sh ../test/nosetests --with-coverage --cover-branches -e 'probabilistic' ../test/test_*.py ../test/medium_test_*.py test/*/*.py > /dev/null
after_script:
  - bash <(curl -s https://codecov.io/bash)
